declare module 'nodemailer';
declare module 'ws';
declare module 'qrcode';
declare module 'formidable';
declare module 'morgan';
declare module 'cors';
declare module 'uuid';
declare module 'multer';
declare module 'imap';
